/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carlrstn;

import javax.swing.JOptionPane;

/**
 *
 * @author CL1-PC08
 */
public class activity extends javax.swing.JFrame {

    /**
     * Creates new form activity
     */
    public activity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPl1 = new javax.swing.JTextField();
        txtPl2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("[1] - ROCK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 152, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("[2] - PAPER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 152, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("[3] - SCISSOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel4.setText("Player 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel5.setText("Player 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        txtPl1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        getContentPane().add(txtPl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, -1));

        txtPl2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        getContentPane().add(txtPl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/carlrstn/ehe.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1070, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int player1 = Integer.parseInt(txtPl1.getText());
        int player2 = Integer.parseInt(txtPl2.getText());
        
        if (player1 == 1 && player2 == 1)
        {
        JOptionPane.showMessageDialog(null, "DRAW", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 1 && player2 == 2)
        {
        JOptionPane.showMessageDialog(null, "PLAYER 2 WIN", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 1 && player2 == 3)
        {
        JOptionPane.showMessageDialog(null, "PLAYER 1 WIN", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 == 1)
        {
        JOptionPane.showMessageDialog(null, "PLAYER 1 WIN", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 == 2)
        {
        JOptionPane.showMessageDialog(null, "DRAW", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 == 3)
        {
        JOptionPane.showMessageDialog(null, "PLAYER 2 WIN", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 == 1)
        {
        JOptionPane.showMessageDialog(null, "PLAYER 1 WIN", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 == 2)
        {
        JOptionPane.showMessageDialog(null, "PLAYER 2 WIN", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 == 3)
        {
        JOptionPane.showMessageDialog(null, "DRAW", "R.P.S", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "PLEASE INPUT THE RIGHT CHOICE!!!", "WRONG CREDENTIALS!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtPl1;
    private javax.swing.JTextField txtPl2;
    // End of variables declaration//GEN-END:variables
}
