/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carlrstn;

/**
 *
 * @author CL1-PC09
 */
public class restoncrl extends javax.swing.JFrame {

    /**
     * Creates new form restoncrl
     */
    public restoncrl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfRollNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfStudentName1 = new javax.swing.JTextField();
        jtfStudentName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfFathersName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfBirthdate = new javax.swing.JTextField();
        jtfBirthdate1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfBirthdate2 = new javax.swing.JTextField();
        jtfMobileNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfMobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        cbCSE = new javax.swing.JCheckBox();
        rbtnFemale = new javax.swing.JRadioButton();
        cbIT = new javax.swing.JCheckBox();
        cbECE = new javax.swing.JCheckBox();
        cbCivil = new javax.swing.JCheckBox();
        cbMech = new javax.swing.JCheckBox();
        cbSelectCourse = new javax.swing.JComboBox<>();
        btnChooseFile = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfCity = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfAddress = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 30)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("STUDENT REGISTRATION FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Roll No. :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 133, -1, -1));

        jtfRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRollNoActionPerformed(evt);
            }
        });
        getContentPane().add(jtfRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 130, 330, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 173, -1, -1));

        jtfStudentName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStudentName1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtfStudentName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 170, 150, -1));

        jtfStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStudentNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 170, 151, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Student Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 173, -1, -1));

        jtfFathersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFathersNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfFathersName, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 210, 330, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Father's Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Date of Birth :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.lightGray);
        jLabel7.setText("(DD-MM-YYYY)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 250, -1, -1));

        jtfBirthdate.setText("Day");
        jtfBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBirthdateActionPerformed(evt);
            }
        });
        getContentPane().add(jtfBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 251, 50, -1));

        jtfBirthdate1.setText("Month");
        jtfBirthdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBirthdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtfBirthdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 251, 50, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 254, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 254, -1, -1));

        jtfBirthdate2.setText("Year");
        jtfBirthdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBirthdate2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtfBirthdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 251, 90, -1));

        jtfMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMobileNoActionPerformed(evt);
            }
        });
        getContentPane().add(jtfMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 291, 276, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Mobile No. :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 291, -1, -1));

        jtfMobile.setText("+63");
        jtfMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMobileActionPerformed(evt);
            }
        });
        getContentPane().add(jtfMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 291, 38, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("-");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 294, -1, -1));

        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 331, 331, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Email ID :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 334, -1, -1));

        jtfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 365, 331, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Password :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 368, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Gender :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Course :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 489, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Department :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 449, -1, -1));

        rbtnMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnMale.setText("Male");
        getContentPane().add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 405, -1, -1));

        cbCSE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCSE.setText("CSE");
        getContentPane().add(cbCSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 444, -1, -1));

        rbtnFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnFemale.setText("Female");
        getContentPane().add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 405, -1, -1));

        cbIT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbIT.setText("IT");
        getContentPane().add(cbIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 444, -1, -1));

        cbECE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbECE.setText("ECE");
        cbECE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbECEActionPerformed(evt);
            }
        });
        getContentPane().add(cbECE, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 444, -1, -1));

        cbCivil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCivil.setText("Civil");
        getContentPane().add(cbCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 444, -1, -1));

        cbMech.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMech.setText("Mech");
        getContentPane().add(cbMech, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 444, -1, -1));

        cbSelectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbSelectCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 486, 331, -1));

        btnChooseFile.setBackground(java.awt.SystemColor.activeCaption);
        btnChooseFile.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnChooseFile.setText("Choose File");
        getContentPane().add(btnChooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 526, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Student Photo :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 527, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("City :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 568, -1, -1));

        jtfCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCityActionPerformed(evt);
            }
        });
        getContentPane().add(jtfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 565, 340, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Address :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 647, -1, -1));

        jtfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jtfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 605, 340, 100));

        btnRegister.setBackground(java.awt.SystemColor.activeCaption);
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 723, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\CL1-PC09\\Downloads\\bg.jpg")); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRollNoActionPerformed

    private void jtfStudentName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStudentName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStudentName1ActionPerformed

    private void jtfStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStudentNameActionPerformed

    private void jtfFathersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFathersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFathersNameActionPerformed

    private void jtfBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBirthdateActionPerformed

    private void jtfBirthdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBirthdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBirthdate1ActionPerformed

    private void jtfBirthdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBirthdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBirthdate2ActionPerformed

    private void jtfMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMobileNoActionPerformed

    private void jtfMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMobileActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPasswordActionPerformed

    private void cbECEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbECEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbECEActionPerformed

    private void jtfCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCityActionPerformed

    private void jtfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(restoncrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(restoncrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(restoncrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(restoncrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restoncrl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnChooseFile;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox cbCSE;
    private javax.swing.JCheckBox cbCivil;
    private javax.swing.JCheckBox cbECE;
    private javax.swing.JCheckBox cbIT;
    private javax.swing.JCheckBox cbMech;
    private javax.swing.JComboBox<String> cbSelectCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfBirthdate;
    private javax.swing.JTextField jtfBirthdate1;
    private javax.swing.JTextField jtfBirthdate2;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFathersName;
    private javax.swing.JTextField jtfMobile;
    private javax.swing.JTextField jtfMobileNo;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfRollNo;
    private javax.swing.JTextField jtfStudentName;
    private javax.swing.JTextField jtfStudentName1;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    // End of variables declaration//GEN-END:variables
}
